//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yyyooolo
{
    using System;
    using System.Collections.Generic;
    
    public partial class towary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public towary()
        {
            this.fak_sprze = new HashSet<fak_sprze>();
            this.fak_zak = new HashSet<fak_zak>();
        }
    
        public int id_towaru { get; set; }
        public string nazwa_towaru { get; set; }
        public string symbol { get; set; }
        public string stan_poczatkowy { get; set; }
        public double cena_zakupu { get; set; }
        public double stawka_vat { get; set; }
        public double marza { get; set; }
        public double cena_sprzedazy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fak_sprze> fak_sprze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fak_zak> fak_zak { get; set; }
    }
}
